use_frameworks!

target 'CoatySwift_Example' do
  pod 'CoatySwift', :path => '../'

  target 'CoatySwift_Tests' do
    inherit! :search_paths
    
    # Testing dependencies.
    pod 'Quick'
    pod 'Nimble'
    
  end
  
  # Compile dependencies with Swift 4.2 to avoid incompatibilities.
  # CoatySwift itself compiled with Swift 5.
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['XCGLogger', 'CocoaMQTT', 'RxSwift', 'RxCocoa'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.2'
              end
          end
      end
  end

end
