use_frameworks!

target 'CoatySwift_Example' do
  pod 'CoatySwift', :path => '../'

  target 'CoatySwift_Tests' do
    inherit! :search_paths
    
    # Testing dependencies.
    pod 'Quick'
    pod 'Nimble'
    
  end
end
