output: docs/swiftdoc
xcodebuild_arguments: -scheme,CoatySwift
author: Siemens AG
author_url: https://coaty.io
github_url: https://github.com/coatyio/coaty-swift
module: CoatySwift
podspec: CoatySwift.podspec
min_acl: public
use_safe_filenames: true
